layout_spectrum: 1
color:
  saturation: 0.7277121
  brandStrength: 0.01442965
  lightness: 0.5064447
  rhythmicContrast: 0.5161117
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
typography_spectrum: 0.06390974
name: Mijn Kids
